# Generated by Django 5.1.5 on 2025-02-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled Note', max_length=255),
        ),
    ]
